<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sycota.Domain\Sycota.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\gogo1\Documents\GitHub\SycotaWebPlatform\Sycota.Application\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\gogo1\Documents\GitHub\SycotaWebPlatform\Sycota.Application\.editorconfig" />
  </ItemGroup>

</Project>
